name: Check PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '16.14.2'
          
      - name: Install dependencies
        run: npm install --force
      
      - name: Run check
        run: npm run lint:check
      
      - name: Build
        run: npm run build